/* Çevre v2: profil, medya paylaşımı ve sahiplik kontrolleri. */
Object.assign(icons,{reels:'<rect x="3" y="3" width="18" height="18" rx="4"/><path d="m10 8 6 4-6 4zM3 7h18"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',list:'<path d="M8 5h13M8 12h13M8 19h13M3 5h1M3 12h1M3 19h1"/>',camera:'<path d="M3 7h4l2-3h6l2 3h4v13H3z"/><circle cx="12" cy="13" r="4"/>',share:'<path d="m12 3 4 4M12 3 8 7M12 3v12M5 11v10h14V11"/>',send:'<path d="m3 3 18 9-18 9 3-9zM6 12h15"/>',edit:'<path d="m16 3 5 5-12 12H4v-5zM13 6l5 5"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/>'});
let viewedId=null,profileTab='posts',profileMode='grid',profileCache=null,profileRequest=0,composeItems=[],editingPost=null,composeToken=0,deletingId=null,detailPostId=null,reelObserver=null,routeApplied=false,uploadBusy=false;
const profileColumns='id,display_name,username,bio,avatar_path,cover_path,created_at';
function user(id){if(id===0||id===myId)return{id:0,name:state.name,handle:state.username||'uye'+myId,initials:state.name.split(' ').map(x=>x[0]||'').join('').slice(0,2),style:'',photo:state.profilePhoto,bio:state.bio,cover:state.coverPhoto,createdAt:state.createdAt};const u=users.find(u=>u.id===id);if(u)return u;const p=allProfiles.find(p=>p.id===id);return p?profileUser(p):{id,name:'Kullanıcı',handle:'uye'+id,initials:'K',style:''}}
function profileUser(p){return{id:p.id,name:p.display_name,handle:p.username||'uye'+p.id,initials:p.display_name.split(' ').map(x=>x[0]||'').join('').slice(0,2),style:'av4',photo:imageUrl(p.avatar_path),bio:p.bio,cover:imageUrl(p.cover_path),createdAt:p.created_at}}
function personLink(u){const id=u.id===0?myId:u.id;return '<button class="person-link" onclick="openProfile('+id+')">'+avatar(u)+'<span class="person-meta"><span class="name">'+esc(u.name)+'</span><br><small>@'+esc(u.handle)+'</small></span></button>'}
function mediaFor(p){if(p.media?.length)return p.media;if(p.imagePath)return[{path:p.imagePath,bucket:'cevre-photos',kind:'image'}];return[]}
function mediaURL(m){return db.storage.from(m.bucket||'cevre-media').getPublicUrl(m.path).data.publicUrl}
function isVideo(p){return mediaFor(p).some(m=>m.kind==='video')}
function empty(title,text,action=''){return '<div class="card empty">'+icon('image')+'<h2>'+esc(title)+'</h2><p>'+esc(text)+'</p>'+action+'</div>'}
function safeID(id){return Number.isSafeInteger(Number(id))&&Number(id)>0?Number(id):null}
function go(v){if(v==='profile'){openProfile(myId);return}if(v!=='home'&&!requireLogin())return;view=v;query='';$('search').value='';render();window.scrollTo(0,0)}
async function openProfile(id){if(!requireLogin())return;id=safeID(id)||myId;viewedId=id;view='profile';profileTab='posts';query='';profileCache=null;$('peopleDialog').close();closePost();render();window.scrollTo(0,0)}
function suggestions(){ $('suggestions').innerHTML=users.length?users.slice(0,5).map(u=>'<div class="suggestion">'+personLink(u)+'<button class="secondary" onclick="follow('+u.id+')">'+(state.following.includes(u.id)?'Takiptesin':'Takip et')+'</button></div>').join(''):'<p class="muted">'+(session?'Çevrene yeni insanlar katıldıkça burada görünecek.':'İnsanlarla tanışmak için giriş yap.')+'</p>' }
function preserveDrafts(){if($('composeText')&&$('composeDialog').open){} }
function render(){
 clearInterval(chatTimer);chatTimer=null;if(reelObserver){reelObserver.disconnect();reelObserver=null}renderAccountBar();
 if(session&&!routeApplied){routeApplied=true;const params=new URLSearchParams(location.search);const id=safeID(params.get('profile'));if(id){view='profile';viewedId=id}const post=safeID(params.get('post'));if(post)setTimeout(()=>openPost(post),50)}
 $('nav').innerHTML=[['home','Ana sayfa'],['explore','Keşfet'],['reels','Videolar'],['messages','Mesajlar'],['notifications','Bildirimler'],['saved','Kaydedilenler'],['profile','Profilim']].map(([id,label])=>'<button data-nav="'+id+'" class="'+(view===id?'active':'')+'" onclick="go(\''+id+'\')">'+icon(id)+'<span class="label">'+label+'</span></button>').join('');
 $('sideName').textContent=state.name;$('sideHandle').textContent=session?'@'+user(0).handle:'Misafir';const a=avatar(user(0));$('sideAvatar').innerHTML=a.slice(a.indexOf('>')+1,-6);suggestions();
 const m=$('main');if(!session){m.innerHTML='<div class="card landing"><span class="eyebrow">SENİN ÇEVREN</span><h1>Birlikte daha yakın.</h1><p>Anlarını paylaş, yeni insanlarla tanış.<br>Kendi hikâyene yer aç.</p>'+(db?'':'<p class="authintro">Üyelik bağlantısı henüz kurulmadı.</p>')+'<div class="row"><button class="primary" onclick="showAuth(\'signup\')">Hesap oluştur</button><button class="secondary" onclick="showAuth(\'login\')">Giriş yap</button></div></div>';return}
 if(view==='profile'){renderProfile();return}if(view==='messages'){renderChat();return}if(view==='reels'){renderReels();return}
 if(view==='notifications'){m.innerHTML=pageTitle('Bildirimler','Çevrenden haberler.')+'<div class="card pad">'+(state.notices.length?state.notices.map(n=>'<div class="notice row">'+icon('notifications')+'<span>'+esc(n)+'</span></div>').join(''):'<p class="muted">Henüz bildirim yok.</p>')+'</div>';return}
 m.innerHTML=pageTitle(view==='explore'?'Keşfet':view==='saved'?'Kaydedilenler':'Akış',view==='home'?'Çevrende bugün neler oluyor?':view==='explore'?'Yeni insanlar, yeni hikâyeler.':'Tekrar dönmek istediğin paylaşımlar.');
 if(view==='home')m.innerHTML+=(users.length?'<div class="member-strip">'+[{...user(0),id:myId},...users.slice(0,9)].map(u=>'<button onclick="openProfile('+u.id+')">'+avatar(u)+'<small>'+esc(u.name.split(' ')[0])+'</small></button>').join('')+'</div>':'')+composerStart()+'<div class="tabs"><button class="'+(tab==='all'?'active':'')+'" onclick="tab=\'all\';render()">Senin için</button><button class="'+(tab==='following'?'active':'')+'" onclick="tab=\'following\';render()">Takip ettiklerin</button></div>';
 if(view==='explore'){m.innerHTML+='<input class="field explore-search" type="search" id="exploreSearch" value="'+esc(query)+'" placeholder="İsim veya kullanıcı adı ara…" aria-label="Kişi ve gönderi ara"><div style="height:20px"></div><div class="people-grid">'+users.filter(u=>(u.name+' '+u.handle).toLocaleLowerCase('tr').includes(query)).map(u=>'<div class="people-card"><button class="person-link" onclick="openProfile('+u.id+')">'+avatar(u)+'<h3>'+esc(u.name)+'</h3><small>@'+esc(u.handle)+'</small></button><p>'+esc(u.bio||'Çevre’ye yeni katıldı.')+'</p><div class="row"><button class="'+(state.following.includes(u.id)?'secondary':'primary')+'" onclick="follow('+u.id+')">'+(state.following.includes(u.id)?'Takiptesin':'Takip et')+'</button><button class="iconbtn" onclick="chatUser='+u.id+';go(\'messages\')" aria-label="Mesaj yaz">'+icon('messages')+'</button></div></div>').join('')+'</div>'}
 const posts=state.posts.filter(p=>(view!=='saved'||state.saved.includes(p.id))&&(view!=='home'||tab!=='following'||state.following.includes(p.authorId))&&((p.text+' '+user(p.user).name).toLocaleLowerCase('tr').includes(query)));
 if(view==='explore')m.innerHTML+=posts.length?'<div class="post-grid">'+posts.map(gridTile).join('')+'</div>':empty('Henüz sonuç yok','Aramanı değiştir veya ilk paylaşımını oluştur.');else m.innerHTML+=posts.length?posts.map(p=>postHTML(p)).join(''):empty(view==='saved'?'Favori anlarına yer aç.':'Yeni bir hikâye başlat.',view==='saved'?'Gönderilerdeki kaydet düğmesiyle burada biriktirebilirsin.':tab==='following'?'Takip ettiğin insanların paylaşımları burada görünecek.':'İlk fotoğraf, video veya düşünceni çevrenle paylaş.',view==='saved'?'':'<button class="primary" onclick="openComposer()">Yeni paylaşım</button>');
 if(state.posts.length>=feedLimit)m.innerHTML+='<div class="loadmore"><button class="secondary" onclick="loadMore()">Daha fazla paylaşım</button></div>';
 if(view==='explore')$('exploreSearch').oninput=e=>{const pos=e.target.selectionStart;query=e.target.value.toLocaleLowerCase('tr');$('search').value=e.target.value;render();$('exploreSearch').focus();if(pos!==null)$('exploreSearch').setSelectionRange(pos,pos)};
}
function pageTitle(title,sub){return '<div class="topline"><div><h1>'+esc(title)+'</h1><div class="greeting">'+esc(sub)+'</div></div><button class="iconbtn" onclick="refreshFeed()" aria-label="Yenile">↻</button></div>'}
function composerStart(){return '<div class="card"><div class="composer-start">'+avatar(user(0))+'<button class="composer-prompt" onclick="openComposer()">Aklından neler geçiyor, '+esc(state.name.split(' ')[0])+'?</button></div><div class="composer-tools"><button onclick="openComposer()">'+icon('image')+' Fotoğraf</button><button onclick="openComposer()">'+icon('reels')+' Video</button><button class="primary" onclick="openComposer()">Paylaş</button></div></div>'}
async function refreshFeed(){if(!requireLogin()||busy)return;profileCache=null;try{await loadData();render();if(detailPostId)redrawDetail()}catch(e){fail(e)}}
async function loadMore(){feedLimit+=40;await refreshFeed()}
async function hydrateRows(rows){let likes=[],comments=[];const ids=rows.map(p=>p.id);if(ids.length){const results=await Promise.all([db.from('likes').select('profile_id,post_id').in('post_id',ids).limit(10000),db.from('comments').select('id,author_id,post_id,body,created_at').in('post_id',ids).order('created_at').limit(2000)]);likes=checked(results[0]);comments=checked(results[1]);const missing=[...new Set(comments.map(c=>c.author_id))].filter(id=>!allProfiles.some(p=>p.id===id));if(missing.length)allProfiles.push(...checked(await db.from('profiles').select(profileColumns).in('id',missing)))}return rows.map(p=>({id:p.id,authorId:p.author_id,user:p.author_id===myId?0:p.author_id,text:p.body,imagePath:p.image_path,media:p.media||[],image:imageUrl(p.image_path),createdAt:p.created_at,likes:likes.filter(l=>l.post_id===p.id&&l.profile_id!==myId).length,comments:comments.filter(c=>c.post_id===p.id).map(c=>({id:c.id,authorId:c.author_id,name:user(c.author_id).name,text:c.body}))}))}
async function loadViewedProfile(id){const token=++profileRequest,version=refreshVersion,owner=session.user.id;try{const results=await Promise.all([db.from('profiles').select(profileColumns).eq('id',id).single(),db.from('posts').select('id,author_id,body,image_path,media,created_at').eq('author_id',id).order('created_at',{ascending:false}).limit(100),db.from('posts').select('id',{count:'exact',head:true}).eq('author_id',id),db.from('follows').select('follower_id',{count:'exact',head:true}).eq('followed_id',id),db.from('follows').select('followed_id',{count:'exact',head:true}).eq('follower_id',id)]);const profile=checked(results[0]),rows=checked(results[1]);for(const r of results.slice(2))checked(r);const posts=await hydrateRows(rows);if(token!==profileRequest||session?.user.id!==owner||viewedId!==id)return;if(!allProfiles.some(p=>p.id===id))allProfiles.push(profile);profileCache={id,version,profile:profileUser(profile),posts,counts:{posts:results[2].count||0,followers:results[3].count||0,following:results[4].count||0}};if(view==='profile')renderProfile()}catch(e){if(token!==profileRequest)return;profileCache={id,version,error:true};if(view==='profile')$('main').innerHTML=empty('Profil yüklenemedi','Bağlantını kontrol edip tekrar deneyebilirsin.','<button class="primary" onclick="openProfile('+id+')">Tekrar dene</button>');console.error(e)}}
function renderProfile(){const id=viewedId||myId;viewedId=id;const ready=profileCache?.id===id&&profileCache.version===refreshVersion;if(!ready){if(!profileCache||profileCache.id!==id||profileCache.version!==refreshVersion){profileCache={id,version:refreshVersion,loading:true};loadViewedProfile(id)}}const cache=profileCache,own=id===myId,u=cache?.profile||(own?user(0):user(id));const count=cache?.counts||{};const posts=cache?.posts||[];const loading=cache?.loading||!ready;
 $('main').innerHTML='<div class="topline"><div><h1>'+(own?'Profilim':esc(u.name))+'</h1><div class="greeting">'+(own?'Senin çevren, senin hikâyen.':'@'+esc(u.handle))+'</div></div><button class="iconbtn" onclick="shareProfile('+id+')" aria-label="Profil bağlantısını paylaş">'+icon('share')+'</button></div><div class="card profile-card"><div class="cover">'+(u.cover?'<img src="'+esc(u.cover)+'" alt="'+esc(u.name)+' kapak fotoğrafı">':'')+(own?'<button class="coveredit" onclick="pickPhoto(\'cover\')">'+icon('camera')+' Kapak '+(u.cover?'değiştir':'ekle')+'</button>':'')+'</div><div class="profile-body"><div class="profile-top"><div class="profilephoto"><div class="avatar profileavatar">'+(u.photo?'<img src="'+esc(u.photo)+'" alt="'+esc(u.name)+' profil fotoğrafı">':esc(u.initials))+'</div>'+'</div><div class="profilebuttons">'+(own?'<button class="secondary" onclick="editProfile()">'+icon('edit')+' Profili düzenle</button><button class="quiet" onclick="logout()">Çıkış yap</button>':'<button class="'+(state.following.includes(id)?'secondary':'primary')+'" onclick="follow('+id+')">'+(state.following.includes(id)?'Takiptesin':'Takip et')+'</button><button class="secondary" onclick="chatUser='+id+';go(\'messages\')">Mesaj</button>')+'</div></div><h2 class="profile-name">'+esc(u.name)+'</h2><div class="profile-handle">@'+esc(u.handle)+'</div>'+(u.bio?'<p class="profile-bio">'+esc(u.bio)+'</p>':'')+'<div class="profile-joined">'+(u.createdAt?new Date(u.createdAt).toLocaleDateString('tr-TR',{month:'long',year:'numeric'})+' tarihinde katıldı.':'')+'</div><div class="stats"><div><b>'+(count.posts??'…')+'</b><small>Gönderi</small></div><button onclick="showPeople('+id+',\'followers\')"><b>'+(count.followers??'…')+'</b><small>Takipçi</small></button><button onclick="showPeople('+id+',\'following\')"><b>'+(count.following??'…')+'</b><small>Takip edilen</small></button></div></div></div><div class="profile-content-header"><div class="tabs"><button class="'+(profileTab==='posts'?'active':'')+'" onclick="profileTab=\'posts\';renderProfile()">Gönderiler</button><button class="'+(profileTab==='videos'?'active':'')+'" onclick="profileTab=\'videos\';renderProfile()">Videolar</button>'+(own?'<button class="'+(profileTab==='saved'?'active':'')+'" onclick="profileTab=\'saved\';renderProfile()">Kaydedilenler</button>':'')+'</div><div class="view-switch"><button class="'+(profileMode==='grid'?'active':'')+'" onclick="profileMode=\'grid\';renderProfile()" aria-label="Izgara görünümü">'+icon('grid')+'</button><button class="'+(profileMode==='list'?'active':'')+'" onclick="profileMode=\'list\';renderProfile()" aria-label="Liste görünümü">'+icon('list')+'</button></div></div>';
 if(loading){$('main').innerHTML+='<div class="card loading">Paylaşımlar yükleniyor…</div>';return}const filtered=profileTab==='saved'?state.posts.filter(p=>state.saved.includes(p.id)):posts.filter(p=>profileTab!=='videos'||isVideo(p));$('main').innerHTML+=filtered.length?(profileMode==='grid'?'<div class="post-grid">'+filtered.map(gridTile).join('')+'</div>':filtered.map(p=>postHTML(p)).join('')):empty(profileTab==='videos'?'Henüz video yok.':profileTab==='saved'?'Henüz kaydedilen yok.':'Henüz paylaşım yok.',own?'Fotoğraf, video veya düşüncelerin için burada yer var.':'Yeni paylaşımlar burada görünecek.',own&&profileTab!=='saved'?'<button class="primary" onclick="openComposer()">Yeni paylaşım</button>':'')}
function gridTile(p){const media=mediaFor(p).filter(m=>m.kind!=='audio'),first=media[0];return '<button class="grid-tile" onclick="openPost('+p.id+')" aria-label="'+esc(user(p.user).name)+' paylaşımını aç">'+(first?(first.kind==='video'?'<video src="'+esc(mediaURL(first))+'#t=0.1" muted playsinline preload="metadata"></video>':'<img src="'+esc(mediaURL(first))+'" loading="lazy" alt="Paylaşım">'):'<div class="grid-text">'+esc(p.text)+'</div>')+(first&&first.kind==='video'?'<span class="grid-corner">'+icon('reels')+'</span>':media.length>1?'<span class="grid-corner">'+icon('image')+'</span>':'')+'<span class="grid-overlay"><span>'+icon('heart')+' '+(p.likes+(state.liked.includes(p.id)?1:0))+'</span><span>'+icon('comment')+' '+p.comments.length+'</span></span></button>'}
function mediaHTML(p,detail=false){const items=mediaFor(p).filter(m=>m.kind!=='audio');if(!items.length)return'';if(items[0].kind==='video')return '<div class="postmedia"><video src="'+esc(mediaURL(items[0]))+'" controls playsinline preload="metadata"></video></div>';const cid='carousel-'+p.id+(detail?'-detail':'');return '<div class="postmedia">'+(items.length>1?'<span class="media-counter">'+items.length+' fotoğraf</span><button class="carousel-prev" onclick="moveCarousel(\''+cid+'\',-1)" aria-label="Önceki fotoğraf">‹</button><button class="carousel-next" onclick="moveCarousel(\''+cid+'\',1)" aria-label="Sonraki fotoğraf">›</button>':'')+'<div class="carousel" id="'+cid+'">'+items.map((m,i)=>'<div class="carousel-slide"><img src="'+esc(mediaURL(m))+'" alt="Paylaşım fotoğrafı '+(i+1)+'" loading="lazy"></div>').join('')+'</div></div>'}
function moveCarousel(id,d){const c=$(id);c.scrollBy({left:d*c.clientWidth,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
function postHTML(p,detail=false){const u=user(p.user),liked=state.liked.includes(p.id),saved=state.saved.includes(p.id),suffix=detail?'-detail':'',own=p.authorId===myId;return '<article class="card post"><div class="posthead">'+personLink(u)+'<div class="post-menu"><details><summary aria-label="Gönderi seçenekleri">⋯</summary><div class="menu-panel"><button onclick="sharePost('+p.id+')">Bağlantıyı paylaş</button>'+(own?'<button onclick="openComposer('+p.id+')">Gönderiyi düzenle</button><button class="delete" onclick="askDelete('+p.id+')">Gönderiyi sil</button>':'')+'</div></details></div></div><p class="posttext">'+esc(p.text)+'</p>'+mediaHTML(p,detail)+musicHTML(p)+'<div class="postbottom"><div class="postactions"><button class="quiet '+(liked?'liked':'')+'" onclick="like('+p.id+')" aria-label="Beğen" aria-pressed="'+liked+'">'+icon('heart')+' '+(p.likes+(liked?1:0))+'</button><button class="quiet" onclick="toggleComments('+p.id+','+detail+')" aria-label="Yorumları aç">'+icon('comment')+' '+p.comments.length+'</button><button class="quiet" onclick="sharePost('+p.id+')" aria-label="Paylaş">'+icon('share')+'</button><button class="quiet save '+(saved?'saved':'')+'" onclick="savePost('+p.id+')" aria-label="Gönderiyi kaydet" aria-pressed="'+saved+'">'+icon('saved')+'</button></div><div class="post-statline">'+formatTime(p.createdAt)+'</div><div class="comments-area" id="comment-'+p.id+suffix+'" '+(detail?'':'hidden')+'>'+p.comments.map(c=>'<div class="comment"><div class="comment-copy"><button class="comment-name" onclick="openProfile('+c.authorId+')">'+esc(c.name)+'</button><p>'+esc(c.text)+'</p></div>'+(c.authorId===myId?'<button class="quiet" onclick="deleteComment('+c.id+','+p.id+')" aria-label="Yorumumu sil">×</button>':'')+'</div>').join('')+'<form class="commentbox" onsubmit="addComment(event,'+p.id+')"><input required maxlength="500" placeholder="Bir yorum ekle…" aria-label="Yorum"><button class="secondary">Gönder</button></form></div></div></article>'}
function findPost(id){return profileCache?.posts?.find(p=>p.id===id)||state.posts.find(p=>p.id===id)}
async function openPost(id){if(!requireLogin())return;detailPostId=id;$('postDetail').innerHTML='<div class="loading">Paylaşım yükleniyor…</div>';$('postDialog').showModal();try{let p=findPost(id);if(!p){const row=checked(await db.from('posts').select('id,author_id,body,image_path,media,created_at').eq('id',id).single());if(!allProfiles.some(u=>u.id===row.author_id))allProfiles.push(checked(await db.from('profiles').select(profileColumns).eq('id',row.author_id).single()));p=(await hydrateRows([row]))[0];state.posts.push(p)}if(detailPostId===id)$('postDetail').innerHTML=postHTML(p,true)}catch(e){$('postDetail').innerHTML=empty('Paylaşım bulunamadı','Bu paylaşım silinmiş olabilir.');console.error(e)}}
function closePost(){detailPostId=null;$('postDialog').close();$('postDetail').querySelectorAll?.('video').forEach(v=>v.pause())}
function redrawDetail(){const p=findPost(detailPostId);if(p&&$('postDialog').open)$('postDetail').innerHTML=postHTML(p,true);else if($('postDialog').open)closePost()}
function toggleComments(id,detail){const c=$('comment-'+id+(detail?'-detail':''));if(c){c.hidden=!c.hidden;if(!c.hidden)c.querySelector('input').focus()}}
async function shareLink(url,title){try{if(navigator.share){await navigator.share({title,url});return}await navigator.clipboard.writeText(url);toast('Bağlantı kopyalandı')}catch(e){if(e.name!=='AbortError')toast('Bağlantı: '+url)}}
function sharePost(id){shareLink(location.origin+'/?post='+id,'Çevre’de bir paylaşım')}
function shareProfile(id){shareLink(location.origin+'/?profile='+id,user(id).name+' · Çevre')}
async function showPeople(id,type){if(!requireLogin())return;$('peopleTitle').textContent=type==='followers'?'Takipçiler':'Takip edilenler';$('peopleList').innerHTML='<div class="loading">Yükleniyor…</div>';$('peopleDialog').showModal();try{const rows=checked(await db.from('follows').select('follower_id,followed_id').eq(type==='followers'?'followed_id':'follower_id',id).limit(200));const ids=rows.map(r=>type==='followers'?r.follower_id:r.followed_id);const profiles=ids.length?checked(await db.from('profiles').select(profileColumns).in('id',ids)):[];profiles.forEach(p=>{if(!allProfiles.some(x=>x.id===p.id))allProfiles.push(p)});$('peopleList').innerHTML=profiles.length?profiles.map(p=>'<div class="suggestion">'+personLink(profileUser(p))+'</div>').join(''):'<p class="muted">Henüz kimse yok.</p>'}catch(e){$('peopleList').textContent='Liste yüklenemedi. Tekrar dene.'}}
async function mutation(action,success){if(!requireLogin()||busy)return false;busy=true;let committed=false;try{await action();committed=true;profileCache=null;await loadData();render();if(detailPostId)redrawDetail();if(success)toast(success);return true}catch(e){if(committed)toast('İşlem kaydedildi, görünüm yenilenemedi. Yenile düğmesini kullan.');else fail(e);return committed}finally{busy=false}}
async function addComment(e,id){e.preventDefault();const text=e.target.querySelector('input').value.trim();if(!text)return;const detail=$('postDialog').open;const ok=await mutation(async()=>checked(await db.from('comments').insert({author_id:myId,post_id:id,body:text})));if(ok){const c=$('comment-'+id+(detail?'-detail':''));if(c)c.hidden=false;if(detailPostId)await openPostFresh(id)}}
async function openPostFresh(id){const row=checked(await db.from('posts').select('id,author_id,body,image_path,media,created_at').eq('id',id).single());const p=(await hydrateRows([row]))[0];const index=state.posts.findIndex(x=>x.id===id);if(index>=0)state.posts[index]=p;if(detailPostId===id)$('postDetail').innerHTML=postHTML(p,true)}
async function deleteComment(id,postId){const p=findPost(postId),c=p?.comments.find(c=>c.id===id);if(!c||c.authorId!==myId)return;await mutation(async()=>checked(await db.from('comments').delete().eq('id',id).eq('author_id',myId)));if(detailPostId)try{await openPostFresh(postId)}catch(e){fail(e)}}
let preparingMedia=false;
function clearItem(item){if(item.preview?.startsWith('blob:'))URL.revokeObjectURL(item.preview)}
function resetSocial(){viewedId=null;profileCache=null;profileRequest++;routeApplied=false;detailPostId=null;composeToken++;composeItems.forEach(clearItem);composeItems=[];editingPost=null;deletingId=null;for(const id of ['composeDialog','postDialog','deleteDialog','peopleDialog','editDialog'])$(id)?.close();if(reelObserver)reelObserver.disconnect();$('composeText').value='';$('postDetail').innerHTML=''}
function closeComposer(){if(uploadBusy)return;$('composeDialog').close();$('mediaPreviews').querySelectorAll('video,audio').forEach(v=>v.pause())}
function renderPreviews(){ $('mediaPreviews').innerHTML=composeItems.map((item,i)=>'<div class="preview-tile">'+(item.kind==='audio'?'<div class="audio-preview">♫<small>'+esc(item.title||'Müzik')+'</small><audio controls src="'+esc(item.preview)+'"></audio></div>':item.kind==='video'?'<video src="'+esc(item.preview)+'" muted playsinline preload="metadata"></video>':'<img src="'+esc(item.preview)+'" alt="Seçilen fotoğraf '+(i+1)+'">')+'<button class="preview-remove" type="button" onclick="removeDraftMedia('+i+')" aria-label="Medyayı kaldır">×</button></div>').join('');$('dropzone').hidden=composeItems.filter(x=>x.kind!=='audio').length>=6||composeItems.some(x=>x.kind==='video');$('composeCount').textContent=$('composeText').value.length+' / 2000'}
function removeDraftMedia(index){if(uploadBusy||preparingMedia)return;clearItem(composeItems[index]);composeItems.splice(index,1);renderPreviews()}
function openComposer(id=null){if(!requireLogin()||uploadBusy)return;if($('composeDialog').open&&editingPost===id)return;if(id!==editingPost){composeToken++;composeItems.forEach(clearItem);composeItems=[];$('composeText').value=''}if(id){const p=findPost(id);if(!p||p.authorId!==myId){toast('Yalnızca kendi paylaşımını düzenleyebilirsin.');return}if(editingPost!==id||!composeItems.length){composeItems=mediaFor(p).map(m=>({...m,saved:true,preview:mediaURL(m)}));$('composeText').value=p.text}}editingPost=id;$('composeTitle').textContent=id?'Paylaşımı düzenle':'Yeni paylaşım';$('composeSubmit').textContent=id?'Değişiklikleri kaydet':'Paylaş';$('composeAuthor').innerHTML=avatar(user(0))+'<div><div class="name">'+esc(state.name)+'</div><small>Çevre üyeleri görebilir.</small></div>';$('composeError').textContent='';renderPreviews();$('composeDialog').showModal();$('composeText').focus()}
async function selectMedia(files){if(uploadBusy||preparingMedia)return;const selected=Array.from(files);if(!selected.length)return;const video=selected.some(f=>f.type.startsWith('video/'));if(video&&(selected.length!==1||composeItems.length)){toast('Video tek başına paylaşılır. Fotoğrafları kaldırıp bir video seç.');return}if(composeItems.some(x=>x.kind==='video')){toast('Video paylaşımına başka medya eklenemez.');return}if(composeItems.filter(x=>x.kind!=='audio').length+selected.length>6){toast('Bir paylaşımda en fazla 6 fotoğraf olabilir.');return}const token=composeToken;preparingMedia=true;$('composeSubmit').disabled=true;$('composeError').textContent='Medya hazırlanıyor…';const added=[];try{for(const f of selected){if(f.type==='video/mp4'||f.type==='video/webm'){if(f.size>20*1024*1024)throw new Error('Video en fazla 20 MB olabilir.');added.push({kind:'video',blob:f,preview:URL.createObjectURL(f),mime:f.type})}else{const data=await compressPhoto(f,'posts');const blob=await(await fetch(data)).blob();added.push({kind:'image',blob,preview:URL.createObjectURL(blob),mime:'image/jpeg'})}}if(token!==composeToken){added.forEach(clearItem);return}composeItems.push(...added);renderPreviews();$('composeError').textContent=''}catch(e){added.forEach(clearItem);$('composeError').textContent=e.message||'Medya hazırlanamadı.'}finally{preparingMedia=false;$('composeSubmit').disabled=false}}
$('mediaInput').onchange=e=>{const files=Array.from(e.target.files);e.target.value='';selectMedia(files)};
$('composeText').oninput=renderPreviews;
$('dropzone').ondragover=e=>{e.preventDefault();$('dropzone').classList.add('drag')};$('dropzone').ondragleave=()=>{$('dropzone').classList.remove('drag')};$('dropzone').ondrop=e=>{e.preventDefault();$('dropzone').classList.remove('drag');selectMedia(e.dataTransfer.files)};
async function removeStoredMedia(items){const groups={};for(const item of items){if(!item?.path||!['cevre-media','cevre-photos'].includes(item.bucket))continue;(groups[item.bucket]||=[]).push(item.path)}let clean=true;for(const [bucket,paths]of Object.entries(groups)){const result=await db.storage.from(bucket).remove([...new Set(paths)]);if(result.error){console.error(result.error);clean=false}}return clean}
$('composeForm').onsubmit=async e=>{e.preventDefault();if(!requireLogin()||uploadBusy||busy||preparingMedia)return;const text=$('composeText').value.trim();if(!text&&!composeItems.length){$('composeError').textContent='Bir şeyler yaz veya medya ekle.';return}if(typeof publishStatus==='function'&&statusMode){await publishStatus();return}if(composeItems.some(m=>m.kind==='audio')&&!composeItems.some(m=>m.kind==='image')){$('composeError').textContent='Müzik için en az bir fotoğraf ekle.';return}const editing=editingPost,previous=editing?mediaFor(findPost(editing)):[],snapshot=[...composeItems],uploaded=[];uploadBusy=true;busy=true;$('composeSubmit').disabled=true;$('composeSubmit').textContent='Yükleniyor…';$('composeError').textContent='';let committed=false;try{const media=[];for(let i=0;i<snapshot.length;i++){const item=snapshot[i];if(item.saved){media.push({kind:item.kind,bucket:item.bucket,path:item.path,title:item.title||''});continue}const ext=item.kind==='audio'?audioExtension(item.mime):item.mime==='video/webm'?'webm':item.kind==='video'?'mp4':'jpg';const path=session.user.id+'/posts/'+crypto.randomUUID()+'.'+ext;$('composeSubmit').textContent='Yükleniyor '+(i+1)+' / '+snapshot.length;checked(await db.storage.from('cevre-media').upload(path,item.blob,{contentType:item.mime,upsert:false}));const record={kind:item.kind,bucket:'cevre-media',path,title:item.title||''};media.push(record);uploaded.push(record)}if(editing){const result=checked(await db.from('posts').update({body:text,media,image_path:null}).eq('id',editing).eq('author_id',myId).select('id'));if(!result.length)throw new Error('Paylaşım bulunamadı veya düzenleme yetkin yok.')}else checked(await db.from('posts').insert({author_id:myId,body:text,media,image_path:null}));committed=true;const deleted=previous.filter(old=>!media.some(m=>m.bucket===old.bucket&&m.path===old.path));let cleaned=true;if(deleted.length)cleaned=await removeStoredMedia(deleted);composeItems.forEach(clearItem);composeItems=[];editingPost=null;$('composeText').value='';$('composeDialog').close();profileCache=null;await loadData();render();if(detailPostId)await openPostFresh(detailPostId);toast(cleaned?(editing?'Paylaşım güncellendi':'Paylaşımın çevrende!'):'Paylaşım güncellendi; eski medya temizliği tamamlanamadı.')}catch(error){console.error(error);if(!committed){if(error.code||error.status)await removeStoredMedia(uploaded);$('composeError').textContent=(error.code==='PGRST204'||error.code==='42703'||/column|bucket.*not found/i.test(error.message||''))?'Supabase’de upgrade-v2.sql güncellemesini çalıştırmalısın.':error.message||'Paylaşım kaydedilemedi. Tekrar dene.'}else toast('Paylaşım kaydedildi. Görünümü yenilemek için Yenile düğmesini kullan.')}finally{uploadBusy=false;busy=false;$('composeSubmit').disabled=false;$('composeSubmit').textContent=editingPost?'Değişiklikleri kaydet':'Paylaş'}};
function askDelete(id){const p=findPost(id);if(!p||p.authorId!==myId){toast('Yalnızca kendi paylaşımını silebilirsin.');return}deletingId=id;$('deleteError').textContent='';$('deleteDialog').showModal()}
async function confirmDelete(){if(!requireLogin()||busy||!deletingId)return;const id=deletingId,p=findPost(id);if(!p||p.authorId!==myId)return;busy=true;$('deleteConfirm').disabled=true;let committed=false;try{const result=checked(await db.from('posts').delete().eq('id',id).eq('author_id',myId).select('id'));if(!result.length)throw new Error('Gönderi bulunamadı veya silme yetkin yok.');committed=true;const cleaned=await removeStoredMedia(mediaFor(p));$('deleteDialog').close();deletingId=null;if(detailPostId===id)closePost();if(editingPost===id){composeItems.forEach(clearItem);composeItems=[];editingPost=null;$('composeText').value='';$('composeDialog').close()}profileCache=null;await loadData();render();toast(cleaned?'Paylaşım silindi':'Paylaşım silindi; medya dosyası temizliği tamamlanamadı.')}catch(e){if(committed){$('deleteDialog').close();toast('Paylaşım silindi. Görünümü yenilemek için Yenile düğmesini kullan.')}else $('deleteError').textContent=e.message||'Gönderi silinemedi. Tekrar dene.'}finally{busy=false;$('deleteConfirm').disabled=false}}
function editProfile(){if(!requireLogin())return;$('editName').value=state.name;$('editBio').value=state.bio;$('editUsername').value=state.username||'';$('editError').textContent='';$('editDialog').showModal()}
$('editForm').onsubmit=async e=>{e.preventDefault();const name=$('editName').value.trim(),bio=$('editBio').value.trim(),username=$('editUsername').value.trim().toLowerCase();if(!name||name.length>40||bio.length>180)return;if(username&&!/^[a-z0-9_.]{3,24}$/.test(username)){$('editError').textContent='Kullanıcı adı 3–24 karakter olmalı. Küçük harf, sayı, nokta ve alt çizgi kullan.';return}if(busy)return;const button=e.target.querySelector('.primary');button.disabled=true;busy=true;let committed=false;try{checked(await db.from('profiles').update({display_name:name,bio,username:username||null}).eq('id',myId));committed=true;profileCache=null;await loadData();render();$('editDialog').close();toast('Profilin güncellendi')}catch(err){$('editError').textContent=committed?'Profilin kaydedildi. Sayfayı yenile.':err.code==='23505'?'Bu kullanıcı adı alınmış. Başka bir ad dene.':'Profil kaydedilemedi. Bağlantını ve SQL güncellemesini kontrol et.'}finally{button.disabled=false;busy=false}};
function renderReels(){const videos=state.posts.filter(isVideo);$('main').innerHTML=pageTitle('Videolar','Çevrenden hareketli anlar.')+(videos.length?'<div class="reels-feed">'+videos.map(p=>{const liked=state.liked.includes(p.id),u=user(p.user),m=mediaFor(p)[0];return '<article class="reel"><video id="reel-video-'+p.id+'" src="'+esc(mediaURL(m))+'" muted playsinline loop preload="metadata" tabindex="0" aria-label="'+esc(u.name)+' videosu" onclick="toggleReel('+p.id+')"></video><button class="reel-play" onclick="toggleReel('+p.id+')" aria-label="Videoyu oynat veya duraklat">▷</button><div class="reel-caption">'+personLink(u)+'<p>'+esc(p.text)+'</p></div><div class="reel-actions"><div><button class="'+(liked?'liked':'')+'" onclick="likeReel('+p.id+')" aria-label="Beğen">'+icon('heart')+'</button><small id="reel-like-'+p.id+'">'+(p.likes+(liked?1:0))+'</small></div><button onclick="openPost('+p.id+')" aria-label="Yorumlar">'+icon('comment')+'</button><button onclick="sharePost('+p.id+')" aria-label="Paylaş">'+icon('share')+'</button></div></article>'}).join('')+'</div>':empty('Henüz video yok.','İlk videonu paylaş, çevrene yeni bir an ekle.','<button class="primary" onclick="openComposer()">Video paylaş</button>'));
 if(videos.length&&'IntersectionObserver'in window){reelObserver=new IntersectionObserver(entries=>{for(const entry of entries){const v=entry.target;if(entry.isIntersecting&&!$('postDialog').open)v.play().catch(()=>{});else v.pause()}},{root:document.querySelector('.reels-feed'),threshold:.65});document.querySelectorAll('.reel video').forEach(v=>reelObserver.observe(v))}}
function toggleReel(id){const v=$('reel-video-'+id);if(!v)return;if(v.paused)v.play().catch(()=>toast('Videoyu açmak için tekrar dokun.'));else v.pause()}
async function likeReel(id){if(!requireLogin()||busy)return;busy=true;try{const liked=state.liked.includes(id);checked(await(liked?db.from('likes').delete().eq('profile_id',myId).eq('post_id',id):db.from('likes').insert({profile_id:myId,post_id:id})));if(liked)state.liked=state.liked.filter(x=>x!==id);else state.liked.push(id);const count=$('reel-like-'+id);if(count){const p=findPost(id);count.textContent=p.likes+(liked?0:1);count.previousElementSibling.classList.toggle('liked',!liked)}}catch(e){fail(e)}finally{busy=false}}
// Profil fotoğrafı değişiminden sonra da kullanıcı adı ve kapak doğru yüklenir.
$('search').oninput=e=>{query=e.target.value.toLocaleLowerCase('tr').trim();view='explore';render()};
$('postDialog').addEventListener('close',()=>{$('postDetail').querySelectorAll('video,audio').forEach(v=>v.pause())});
$('composeDialog').addEventListener('cancel',e=>{if(uploadBusy)e.preventDefault()});
$('deleteDialog').addEventListener('cancel',e=>{if(busy&&deletingId)e.preventDefault()});
window.cevreReady.then(()=>{if(session)render()});
